# Numpy_Assignment_2:: 
# Name: Muhammad Ahsan Farooqui 
# PIAIC ID: PIAIC55329

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
array1D = np.array([0,1,2,3,4,5,6,7,8,9])
arr1 = np.reshape(array1D,(2,5))
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
array1 = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
array2 =        ([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

np.vstack((array1,array2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
array1 = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
array2 =        ([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

np.hstack((array1,array2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
array11 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
np.ravel(array11)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
array11 = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
array11.reshape(15,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [8]:
arayy1 = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
arayy1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [13]:
fivebyfive = np.random.random((5,5))*100
np.square(fivebyfive)

array([[ 518.34930162, 2314.1835772 , 6676.03964176, 3548.14373627,
        1235.55176306],
       [4617.2807978 , 5461.58309642, 3056.0241213 , 1039.47493633,
        6701.87697996],
       [ 184.70382278,  771.61076207, 7003.86154453, 3494.22129595,
        1559.85149487],
       [3489.75174713, 6933.8376965 ,  873.88322039, 7463.44147501,
        6533.47090161],
       [ 103.98524482, 1310.17911894, 2112.95827911, 1590.99371726,
        2591.38372333]])

## Question:8

### Create 5x6 an array and find the mean?

In [14]:
fivebysix = np.random.random((5,6))*100
np.mean(fivebysix)

51.474547593634604

## Question:9

### Find the standard deviation of the previous array in Q8?

In [16]:
np.std(fivebysix)

27.96557203568952

## Question:10

### Find the median of the previous array in Q8?

In [18]:
np.median(fivebysix)

46.99055530136593

## Question:11

### Find the transpose of the previous array in Q8?

In [19]:
np.transpose(fivebysix)

array([[91.05749344, 74.65905728, 99.45869847, 57.05187721, 72.11411593],
       [93.42239396, 88.75992522, 43.54416234, 33.24010704, 90.70357162],
       [23.74847814, 12.52080827, 43.7672307 , 29.68450905, 21.91556077],
       [ 7.34654045, 24.38255444, 56.80324429, 50.2138799 , 41.40107589],
       [65.62206465, 57.41770792, 42.36083693, 29.93508886, 81.09941639],
       [50.30456659,  1.81479547, 96.97900087, 29.51857615, 33.38908958]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [22]:
a = np.random.random((4,4))
sum(np.diagonal(a))

2.054785448955196

## Question:13

### Find the determinant of the previous array in Q12?

In [23]:
np.linalg.det(a)

0.004407156066027845

## Question:14

### Find the 5th and 95th percentile of an array?

In [24]:
np.percentile(a,[5,95])

array([0.12163422, 0.9323472 ])

## Question:15

### How to find if a given array has any null values?

In [29]:
np.isnan(a)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])